name: slim-bloat
on:
  pull_request:
jobs:
  bloat:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: slim-js/slim/action/bloat@v1
        # fail: true   # optional: exit 1 when a fat slimmable dep is added
